//! On-target correctness harness.
//!
//! Runs under QEMU (`cargo run --release`) on an emulated Cortex-M4, and on
//! real hardware unchanged. Two independent checks:
//!
//! 1. **Known-answer tests** — vectors generated by `gen/gen_kat.py` from
//!    Python bignum. Catches a target-specific miscompile that a
//!    backend-vs-backend comparison would miss.
//! 2. **Differential** — assembly vs the portable reference over many
//!    pseudo-random inputs. The portable backend is itself verified against
//!    `num-bigint` by the host test suite, so this transitively pins the
//!    assembly to an independent oracle.
//!
//! Exits non-zero if anything fails, so it works as a CI gate.

#![no_std]
#![no_main]

use cortex_m_rt::entry;
use cortex_m_semihosting::{debug, hprintln};
use mcu_crypto_asm::{backend, p256, p384, Fe, Params};

use panic_semihosting as _;

mod kat;

/// Multiply through the *public* path (whatever backend is selected).
fn mul_via_backend<const N: usize>(f: &Params, a: &[u32; N], b: &[u32; N]) -> [u32; N] {
    let fa = Fe::<N>::from_int(f, a);
    let fb = Fe::<N>::from_int(f, b);
    fa.mul(f, &fb).to_int(f)
}

/// Known-answer test.
fn run_kat<const N: usize>(
    f: &Params,
    name: &str,
    vectors: &[([u32; N], [u32; N], [u32; N])],
) -> u32 {
    let mut fails = 0;
    for (i, (a, b, want)) in vectors.iter().enumerate() {
        let got = mul_via_backend(f, a, b);
        if got != *want {
            hprintln!("  FAIL {} KAT[{}]", name, i);
            hprintln!("    want {:08x?}", want);
            hprintln!("    got  {:08x?}", got);
            fails += 1;
        }
    }
    if fails == 0 {
        hprintln!("  ok   {} KAT ({} vectors)", name, vectors.len());
    }
    fails
}

/// Deterministic xorshift64*, so a failure is always reproducible.
struct Rng(u64);
impl Rng {
    fn next_u32(&mut self) -> u32 {
        let mut x = self.0;
        x ^= x << 13;
        x ^= x >> 7;
        x ^= x << 17;
        self.0 = x;
        (x >> 32) as u32
    }
}

/// Differential test: assembly vs portable, on identical inputs.
///
/// Inputs are reduced by the field conversion, so no bound assumptions are
/// needed on the raw random limbs.
fn run_differential<const N: usize>(f: &Params, name: &str, rounds: u32) -> u32 {
    let mut rng = Rng(0x9E3779B97F4A7C15);
    let mut fails = 0;

    for round in 0..rounds {
        let mut a = [0u32; N];
        let mut b = [0u32; N];
        for i in 0..N {
            a[i] = rng.next_u32();
            b[i] = rng.next_u32();
        }
        // Bring both into range by converting to Montgomery form and back.
        let a = Fe::<N>::from_int(f, &a).to_int(f);
        let b = Fe::<N>::from_int(f, &b).to_int(f);

        // Montgomery-domain operands for a like-for-like comparison.
        let am = Fe::<N>::from_int(f, &a);
        let bm = Fe::<N>::from_int(f, &b);

        let mut want = [0u32; N];
        backend::portable::mul_mont(
            am.as_mont_limbs(),
            bm.as_mont_limbs(),
            f.p,
            f.n0inv,
            &mut want,
        );

        let mut got = [0u32; N];
        let took_asm = asm_mul(am.as_mont_limbs(), bm.as_mont_limbs(), f, &mut got);

        if !took_asm {
            hprintln!("  SKIP {} differential: no assembly backend active", name);
            return 0;
        }
        if got != want {
            hprintln!("  FAIL {} differential round {}", name, round);
            hprintln!("    a    {:08x?}", a);
            hprintln!("    b    {:08x?}", b);
            hprintln!("    want {:08x?}", want);
            hprintln!("    got  {:08x?}", got);
            fails += 1;
            if fails > 3 {
                return fails;
            }
        }
    }
    if fails == 0 {
        hprintln!("  ok   {} differential ({} rounds)", name, rounds);
    }
    fails
}

/// Call the assembly backend directly. Returns false if none is compiled in.
#[allow(unused_variables)]

fn run_differential_add_sub<const N: usize>(f: &Params, name: &str, rounds: u32) -> u32 {
    let mut rng = Rng(0x123456789ABCDEF0);
    let mut fails = 0;

    for round in 0..rounds {
        let mut a = [0u32; N];
        let mut b = [0u32; N];
        for i in 0..N {
            a[i] = rng.next_u32();
            b[i] = rng.next_u32();
        }
        let a = Fe::<N>::from_int(f, &a).to_int(f);
        let b = Fe::<N>::from_int(f, &b).to_int(f);

        let mut want_add = [0u32; N];
        backend::portable::add_mod(&a, &b, f.p, &mut want_add);
        let mut got_add = [0u32; N];
        backend::add_mod(&a, &b, f.p, &mut got_add);
        if got_add != want_add {
            hprintln!("  FAIL {} add_mod differential round {}", name, round);
            fails += 1;
            if fails > 3 { return fails; }
        }

        let mut want_sub = [0u32; N];
        backend::portable::sub_mod(&a, &b, f.p, &mut want_sub);
        let mut got_sub = [0u32; N];
        backend::sub_mod(&a, &b, f.p, &mut got_sub);
        if got_sub != want_sub {
            hprintln!("  FAIL {} sub_mod differential round {}", name, round);
            fails += 1;
            if fails > 3 { return fails; }
        }
    }
    if fails == 0 {
        hprintln!("  ok   {} add/sub differential ({} rounds)", name, rounds);
    }
    fails
}

fn run_differential_sqr<const N: usize>(f: &Params, name: &str, rounds: u32) -> u32 {
    let mut rng = Rng(0xCAFEBABE12345678);
    let mut fails = 0;

    for round in 0..rounds {
        let mut a = [0u32; N];
        for i in 0..N {
            a[i] = rng.next_u32();
        }
        let a = Fe::<N>::from_int(f, &a).to_int(f);
        let am = Fe::<N>::from_int(f, &a);

        let mut want = [0u32; N];
        backend::portable::mul_mont(
            am.as_mont_limbs(),
            am.as_mont_limbs(),
            f.p,
            f.n0inv,
            &mut want,
        );

        let mut got = [0u32; N];
        backend::sqr_mont(am.as_mont_limbs(), f.p, f.n0inv, &mut got);

        if got != want {
            hprintln!("  FAIL {} sqr differential round {}", name, round);
            fails += 1;
            if fails > 3 {
                return fails;
            }
        }
    }
    if fails == 0 {
        hprintln!("  ok   {} sqr differential ({} rounds)", name, rounds);
    }
    fails
}

fn asm_mul<const N: usize>(a: &[u32; N], b: &[u32; N], f: &Params, out: &mut [u32; N]) -> bool {
    #[cfg(nistp_asm_cm4)]
    {
        return backend::cortex_m4::try_mul_mont(a, b, f.p, f.n0inv, out);
    }
    #[cfg(not(nistp_asm_cm4))]
    {
        false
    }
}

#[entry]
fn main() -> ! {
    hprintln!("mcu-crypto-asm on-target tests");
    hprintln!("backend: {}", backend::NAME);

    let mut fails = 0;

    // The whole point is to exercise assembly. If the build silently fell back
    // to the portable path, the run is meaningless — say so loudly.
    if backend::NAME == "portable" {
        hprintln!("WARNING: portable backend active; assembly was NOT tested");
    }

    hprintln!("P-256:");
    fails += run_kat::<{ p256::N }>(&p256::FIELD, "p256", &kat::P256_MUL);
    fails += run_differential::<{ p256::N }>(&p256::FIELD, "p256", 500);
    fails += run_differential_sqr::<{ p256::N }>(&p256::FIELD, "p256", 500);
    fails += run_differential_add_sub::<{ p256::N }>(&p256::FIELD, "p256", 500);

    let d = [1u8; 32];
    let mut pk = [0u8; 65];
    p256::derive_public_key(&d, &mut pk).unwrap();
    let msg = [0x42u8; 32];
    let k = [0x77u8; 32];
    let mut r = [0u8; 32];
    let mut s = [0u8; 32];
    p256::ecdsa::sign(&d, &msg, &k, &mut r, &mut s).unwrap();
    if p256::ecdsa::verify(&pk, &msg, &r, &s).is_err() {
        hprintln!("  FAIL p256 ecdsa on-target");
        fails += 1;
    } else {
        hprintln!("  ok   p256 ecdsa sign & verify");
    }

    hprintln!("P-384:");
    fails += run_kat::<{ p384::N }>(&p384::FIELD, "p384", &kat::P384_MUL);
    fails += run_differential::<{ p384::N }>(&p384::FIELD, "p384", 500);
    fails += run_differential_sqr::<{ p384::N }>(&p384::FIELD, "p384", 500);
    fails += run_differential_add_sub::<{ p384::N }>(&p384::FIELD, "p384", 500);

    let d384 = [1u8; 48];
    let mut pk384 = [0u8; 97];
    p384::derive_public_key(&d384, &mut pk384).unwrap();
    let msg384 = [0x42u8; 48];
    let k384 = [0x77u8; 48];
    let mut r384 = [0u8; 48];
    let mut s384 = [0u8; 48];
    p384::ecdsa::sign(&d384, &msg384, &k384, &mut r384, &mut s384).unwrap();
    if p384::ecdsa::verify(&pk384, &msg384, &r384, &s384).is_err() {
        hprintln!("  FAIL p384 ecdsa on-target");
        fails += 1;
    } else {
        hprintln!("  ok   p384 ecdsa sign & verify");
    }

    if fails == 0 {
        hprintln!("ALL PASS");
        debug::exit(debug::EXIT_SUCCESS);
    } else {
        hprintln!("FAILURES: {}", fails);
        debug::exit(debug::EXIT_FAILURE);
    }
    loop {}
}
