//! Cortex-M4 (ARMv7E-M) backend.
//!
//! The assembly lives in `asm/cortex_m4.S`, generated by
//! `gen/gen_asm_cortex_m4.py`. It is built on `UMAAL`, which computes
//! `RdHi:RdLo = Rn*Rm + RdHi + RdLo` in a single cycle and cannot overflow —
//! exactly the CIOS inner step. That one instruction is why Cortex-M4 is so
//! much faster at this than a generic 32-bit core.
//!
//! Also correct (and still a large win) on Cortex-M7 and Cortex-M33.
//!
//! ⚠ Cortex-M3 is ARMv7-M and *has* `UMAAL`, but its multiplier is
//! variable-latency, so this code would not be constant time there. The `cfg`
//! below deliberately requires the DSP extension (`v7`+`dsp`), which M3 lacks.

use core::arch::global_asm;

// `options(raw)`: the template is assembly, not a format string. Without it
// `push {r4-r11, lr}` is parsed as a format placeholder, and the .S file stops
// being usable standalone.
global_asm!(include_str!("../../asm/cortex_m4.S"), options(raw));

extern "C" {
    fn nistp_mul_mont_8(out: *mut u32, a: *const u32, b: *const u32, p: *const u32);
    fn nistp_mul_mont_12(out: *mut u32, a: *const u32, b: *const u32, p: *const u32);
    fn nistp_sqr_mont_8(out: *mut u32, a: *const u32, p: *const u32);
    fn nistp_sqr_mont_12(out: *mut u32, a: *const u32, p: *const u32);
    fn nistp_add_mod_8(out: *mut u32, a: *const u32, b: *const u32, p: *const u32);
    fn nistp_add_mod_12(out: *mut u32, a: *const u32, b: *const u32, p: *const u32);
    fn nistp_sub_mod_8(out: *mut u32, a: *const u32, b: *const u32, p: *const u32);
    fn nistp_sub_mod_12(out: *mut u32, a: *const u32, b: *const u32, p: *const u32);
    fn nistp_div2_12(out: *mut u32, a: *const u32);
}

/// Dispatch to assembly if a routine exists for this limb count.
///
/// Returns `false` when there is no assembly for `a.len()`, so the caller
/// falls back to the portable reference.
#[inline]
pub fn try_mul_mont(a: &[u32], b: &[u32], p: &[u32], n0inv: u32, out: &mut [u32]) -> bool {
    // The assembly hard-codes n0' == 1 (true for both NIST primes). Anything
    // else must not silently take this path.
    if n0inv != 1 {
        return false;
    }
    debug_assert_eq!(b.len(), a.len());
    debug_assert_eq!(p.len(), a.len());
    debug_assert_eq!(out.len(), a.len());

    match a.len() {
        // SAFETY: lengths are checked above, so each pointer is valid for
        // exactly the number of limbs the routine reads/writes. The routines
        // touch no other memory and preserve all callee-saved registers.
        8 if p == crate::params::p256::P => unsafe {
            nistp_mul_mont_8(out.as_mut_ptr(), a.as_ptr(), b.as_ptr(), p.as_ptr());
            true
        },
        12 if p == crate::params::p384::P => unsafe {
            nistp_mul_mont_12(out.as_mut_ptr(), a.as_ptr(), b.as_ptr(), p.as_ptr());
            true
        },
        _ => false,
    }
}

/// Dispatch dedicated squaring to assembly if a routine exists for this limb count.
#[inline]
pub fn try_sqr_mont(a: &[u32], p: &[u32], n0inv: u32, out: &mut [u32]) -> bool {
    if n0inv != 1 {
        return false;
    }
    debug_assert_eq!(p.len(), a.len());
    debug_assert_eq!(out.len(), a.len());

    match a.len() {
        8 if p == crate::params::p256::P => unsafe {
            nistp_sqr_mont_8(out.as_mut_ptr(), a.as_ptr(), p.as_ptr());
            true
        },
        12 if p == crate::params::p384::P => unsafe {
            nistp_sqr_mont_12(out.as_mut_ptr(), a.as_ptr(), p.as_ptr());
            true
        },
        _ => false,
    }
}

#[inline]
pub fn try_add_mod(a: &[u32], b: &[u32], p: &[u32], out: &mut [u32]) -> bool {
    debug_assert_eq!(b.len(), a.len());
    debug_assert_eq!(p.len(), a.len());
    debug_assert_eq!(out.len(), a.len());

    match a.len() {
        8 if p == crate::params::p256::P => unsafe {
            nistp_add_mod_8(out.as_mut_ptr(), a.as_ptr(), b.as_ptr(), p.as_ptr());
            true
        },
        12 if p == crate::params::p384::P => unsafe {
            nistp_add_mod_12(out.as_mut_ptr(), a.as_ptr(), b.as_ptr(), p.as_ptr());
            true
        },
        _ => false,
    }
}

#[inline]
pub fn try_sub_mod(a: &[u32], b: &[u32], p: &[u32], out: &mut [u32]) -> bool {
    debug_assert_eq!(b.len(), a.len());
    debug_assert_eq!(p.len(), a.len());
    debug_assert_eq!(out.len(), a.len());

    match a.len() {
        8 if p == crate::params::p256::P => unsafe {
            nistp_sub_mod_8(out.as_mut_ptr(), a.as_ptr(), b.as_ptr(), p.as_ptr());
            true
        },
        12 if p == crate::params::p384::P => unsafe {
            nistp_sub_mod_12(out.as_mut_ptr(), a.as_ptr(), b.as_ptr(), p.as_ptr());
            true
        },
        _ => false,
    }
}

#[inline]
pub fn try_div2(a: &[u32], p: &[u32], out: &mut [u32]) -> bool {
    if a.len() == 12 && p == crate::params::p384::P {
        unsafe {
            nistp_div2_12(out.as_mut_ptr(), a.as_ptr());
        }
        true
    } else {
        false
    }
}

