//! Curve constants. GENERATED by `gen/gen_params.py` — do not edit.
//!
//! Field elements marked `_MONT` are in Montgomery form (multiplied by
//! R = 2^(32*N) mod p). Everything else is a plain integer.
#![allow(clippy::unreadable_literal)]

/// P256 (256-bit prime field).
pub mod p256 {
    /// Number of 32-bit limbs.
    pub const N: usize = 8;
    /// -p^-1 mod 2^32. Exactly 1 for this prime; asm relies on it.
    pub const N0INV: u32 = 1;

    /// Field modulus p.
    pub const P: [u32; 8] = [
    0xffffffff, 0xffffffff, 0xffffffff, 0x00000000,
    0x00000000, 0x00000000, 0x00000001, 0xffffffff
    ];

    /// Order of the base point.
    pub const ORDER: [u32; 8] = [
    0xfc632551, 0xf3b9cac2, 0xa7179e84, 0xbce6faad,
    0xffffffff, 0xffffffff, 0x00000000, 0xffffffff
    ];

    /// R mod p == 1 in Montgomery form.
    pub const R_MONT: [u32; 8] = [
    0x00000001, 0x00000000, 0x00000000, 0xffffffff,
    0xffffffff, 0xffffffff, 0xfffffffe, 0x00000000
    ];

    /// R^2 mod p. Converts into Montgomery form.
    pub const R2_MONT: [u32; 8] = [
    0x00000003, 0x00000000, 0xffffffff, 0xfffffffb,
    0xfffffffe, 0xffffffff, 0xfffffffd, 0x00000004
    ];

    /// R^3 mod p. Used by Montgomery inversion.
    pub const R3_MONT: [u32; 8] = [
    0x0000000a, 0xfffffffd, 0xfffffff7, 0xffffffed,
    0xfffffffc, 0x00000005, 0x00000001, 0x00000018
    ];

    /// Curve coefficient a = -3, Montgomery form.
    pub const A_MONT: [u32; 8] = [
    0xfffffffc, 0xffffffff, 0xffffffff, 0x00000003,
    0x00000000, 0x00000000, 0x00000004, 0xfffffffc
    ];

    /// Curve coefficient b, Montgomery form.
    pub const B_MONT: [u32; 8] = [
    0x29c4bddf, 0xd89cdf62, 0x78843090, 0xacf005cd,
    0xf7212ed6, 0xe5a220ab, 0x04874834, 0xdc30061d
    ];

    /// Base point x, Montgomery form.
    pub const GX_MONT: [u32; 8] = [
    0x18a9143c, 0x79e730d4, 0x5fedb601, 0x75ba95fc,
    0x77622510, 0x79fb732b, 0xa53755c6, 0x18905f76
    ];

    /// Base point y, Montgomery form.
    pub const GY_MONT: [u32; 8] = [
    0xce95560a, 0xddf25357, 0xba19e45c, 0x8b4ab8e4,
    0xdd21f325, 0xd2e88688, 0x25885d85, 0x8571ff18
    ];

}

/// P384 (384-bit prime field).
pub mod p384 {
    /// Number of 32-bit limbs.
    pub const N: usize = 12;
    /// -p^-1 mod 2^32. Exactly 1 for this prime; asm relies on it.
    pub const N0INV: u32 = 1;

    /// Field modulus p.
    pub const P: [u32; 12] = [
    0xffffffff, 0x00000000, 0x00000000, 0xffffffff,
    0xfffffffe, 0xffffffff, 0xffffffff, 0xffffffff,
    0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff
    ];

    /// Order of the base point.
    pub const ORDER: [u32; 12] = [
    0xccc52973, 0xecec196a, 0x48b0a77a, 0x581a0db2,
    0xf4372ddf, 0xc7634d81, 0xffffffff, 0xffffffff,
    0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff
    ];

    /// R mod p == 1 in Montgomery form.
    pub const R_MONT: [u32; 12] = [
    0x00000001, 0xffffffff, 0xffffffff, 0x00000000,
    0x00000001, 0x00000000, 0x00000000, 0x00000000,
    0x00000000, 0x00000000, 0x00000000, 0x00000000
    ];

    /// R^2 mod p. Converts into Montgomery form.
    pub const R2_MONT: [u32; 12] = [
    0x00000001, 0xfffffffe, 0x00000000, 0x00000002,
    0x00000000, 0xfffffffe, 0x00000000, 0x00000002,
    0x00000001, 0x00000000, 0x00000000, 0x00000000
    ];

    /// R^3 mod p. Used by Montgomery inversion.
    pub const R3_MONT: [u32; 12] = [
    0x00000002, 0xfffffffc, 0x00000002, 0x00000003,
    0xfffffffe, 0xfffffffc, 0x00000005, 0x00000003,
    0xfffffffd, 0xfffffffd, 0x00000002, 0x00000003
    ];

    /// Curve coefficient a = -3, Montgomery form.
    pub const A_MONT: [u32; 12] = [
    0xfffffffc, 0x00000003, 0x00000000, 0xfffffffc,
    0xfffffffb, 0xffffffff, 0xffffffff, 0xffffffff,
    0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff
    ];

    /// Curve coefficient b, Montgomery form.
    pub const B_MONT: [u32; 12] = [
    0x9d412dcc, 0x08118871, 0x7a4c32ec, 0xf729add8,
    0x1920022e, 0x77f2209b, 0x94938ae2, 0xe3374bee,
    0x1f022094, 0xb62b21f4, 0x604fbff9, 0xcd08114b
    ];

    /// Base point x, Montgomery form.
    pub const GX_MONT: [u32; 12] = [
    0x49c0b528, 0x3dd07566, 0xa0d6ce38, 0x20e378e2,
    0x541b4d6e, 0x879c3afc, 0x59a30eff, 0x64548684,
    0x614ede2b, 0x812ff723, 0x299e1513, 0x4d3aadc2
    ];

    /// Base point y, Montgomery form.
    pub const GY_MONT: [u32; 12] = [
    0x4b03a4fe, 0x23043dad, 0x7bb4a9ac, 0xa1bfa8bf,
    0x2e83b050, 0x8bade756, 0x68f4ffd9, 0xc6c35219,
    0x3969a840, 0xdd800226, 0x5a15c5e9, 0x2b78abc2
    ];

}
